language: node_js
node_js:
    - "0.12"
    - "0.10"

before_script:
  - npm install -g webpack karma karma-webpack karma-coverage karma-phantomjs2-launcher karma-sourcemap-loader karma-jasmine jasmine-core

script: karma start
